Feat/product page
flkrasnov/fake-burrberry-frontend pull request #2
Opened 2017-08-01 07:55 UTC by flkrasnov

whole mobile version added and fixed

2017-08-01 12:07 UTC, evgenyrodionov commented
https://rawgit.com/flkrasnov/fake-burrberry-frontend/feat/product-page/index.html

![image](https://user-images.githubusercontent.com/775692/28824528-0dd01e6a-76cb-11e7-8ed1-3d485517c4f0.png)
![image](https://user-images.githubusercontent.com/775692/28824534-18970c82-76cb-11e7-98bf-a305bb915767.png)
![image](https://user-images.githubusercontent.com/775692/28824541-21dc34e8-76cb-11e7-88e2-1c66cae12285.png)
![image](https://user-images.githubusercontent.com/775692/28824548-29cff162-76cb-11e7-9fd9-1689d8fc8f19.png)
![image](https://user-images.githubusercontent.com/775692/28824554-306363c4-76cb-11e7-8390-7724ecf939c9.png)

2017-08-01 12:08 UTC, imevro requested changes
фикси дизайн

бтв, цсс мусорный очень и не под кодгайду

нейминг типа итем — плохой

2017-08-02 18:50 UTC, evgenyrodionov commented
Коммиты не по формату

2017-08-02 18:52 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28889436-ad17d7c2-77cc-11e7-8b26-803860eb6c27.png)
![image](https://user-images.githubusercontent.com/775692/28889449-b4533cde-77cc-11e7-8635-3527e7620b16.png)
![image](https://user-images.githubusercontent.com/775692/28889485-d0277d80-77cc-11e7-802f-fff77ece4d1a.png)
![image](https://user-images.githubusercontent.com/775692/28889515-e89a771e-77cc-11e7-9173-bb7592346371.png)

2017-08-02 18:53 UTC, evgenyrodionov commented
цсс мусорный бтв, почисти его

2017-08-03 08:27 UTC, flkrasnov commented
по поводу цсс, можно пожалуйста пример, что еще сделать для улучшения читаемости?

2017-08-03 12:00 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28920876-54d2ffd4-785c-11e7-9245-0262ad8daf38.png)
![image](https://user-images.githubusercontent.com/775692/28920886-60776fd2-785c-11e7-8e56-53cd6096d06e.png)

2017-08-03 12:01 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28920930-93eb43b6-785c-11e7-9c62-3fafe4d75ed7.png)

![image](https://user-images.githubusercontent.com/775692/28920910-8418d9e4-785c-11e7-984e-342aeb165e46.png)

2017-08-03 12:03 UTC, imevro requested changes
дизайн ↑, цсс стал лучше, красава

2017-08-04 07:53 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28959392-ef565bae-7902-11e7-940b-8334b139fcf7.png)
![image](https://user-images.githubusercontent.com/775692/28959408-f77d7862-7902-11e7-92b9-5f3e218788be.png)
![image](https://user-images.githubusercontent.com/775692/28959422-004ffa6e-7903-11e7-8346-2f83390c7875.png)
![image](https://user-images.githubusercontent.com/775692/28959428-0835ba70-7903-11e7-821d-c7974d4b89c6.png)

2017-08-04 07:55 UTC, imevro requested changes
- Проблемы с описанием
- Суперфикс ширины или высоты картинок

2017-08-04 08:29 UTC, flkrasnov commented
проблемы с описанием решены
суперфикс решен

2017-08-04 13:49 UTC, imevro requested changes

2017-08-04 13:49 UTC, evgenyrodionov commented on main.css
> +  line-height: 0.9375rem;
1рем же, что за меджик намбер

2017-08-04 14:05 UTC, flkrasnov commented on main.css
> +  line-height: 0.9375rem;
лол, поправил

2017-08-04 19:41 UTC, evgenyrodionov commented
На след проверку

2017-08-05 09:39 UTC, imevro approved these changes

2017-08-05 09:39 UTC, evgenyrodionov commented
планшет делай

2017-08-05 10:10 UTC, flkrasnov commented
# !! UPDATE !!
**Разработка планшетной версии переехала в новую ветку: feat/product-page-tablet**
# !! UPDATE !!

2017-08-05 18:52 UTC, evgenyrodionov commented
Шрифты жирные

![image](https://user-images.githubusercontent.com/775692/28997892-4711dc26-7a28-11e7-8eec-40f3569c72b8.png)

2017-08-05 18:53 UTC, imevro requested changes

2017-08-05 18:53 UTC, evgenyrodionov commented on index.html
> +      <ul class="more-links-block">
юл ли только для списков внутри текстов

2017-08-05 18:53 UTC, evgenyrodionov commented on index.html
> +              <a href="">Contact Us</a>
ссылки в нав

2017-08-06 02:47 UTC, flkrasnov commented on index.html
> +              <a href="">Contact Us</a>
1. Полу-жирный шрифт (в макете Raleway-SemiBold, font-weight: 600;) так в коде и установлено, поменял на 500 (medium)
2. Списки для more-liks убрал
3. Обернул футер-навигацию в nav.

2017-08-06 02:52 UTC, flkrasnov commented
1. Полу-жирный шрифт (в макете Raleway-SemiBold, font-weight: 600;) так в коде и установлено, поменял на 500 (medium)
2. Списки для more-liks убрал
3. Обернул футер-навигацию в nav.

2017-08-06 20:56 UTC, imevro approved these changes

2017-08-06 20:56 UTC, merged