Burberry react
flkrasnov/fake-burrberry-frontend pull request #3
Opened 2017-08-09 08:49 UTC by flkrasnov

Divided to components

2017-08-09 09:59 UTC, imevro requested changes
- Тайтлы через react-helmet
- Нормальные manifest.json и package.json
- README.md должен быть про проект
- Нейминг должен быть корректным
- Функции — тупым компонентам, классы — рабочим
- Поставьте prettier
- Архитектура должна быть про продукт

2017-08-09 09:59 UTC, evgenyrodionov commented on src/components/main-section/accordion/accordion-heading.js
> +
пиздец у тебя тут кто-то рассыпал переносы строк

2017-08-09 09:59 UTC, evgenyrodionov commented on src/components/main-section/accordion/accordion-heading.js
> +import React, { Component } from 'react';
зачем ты импортнул Component и не используешь его?

2017-08-09 09:59 UTC, evgenyrodionov commented on src/components/main-section/accordion/accordion.js
> +const accordionHeadings = [
убери

2017-08-09 09:59 UTC, evgenyrodionov commented on src/components/main-section/accordion/accordion.js
> +
да что за хуйня

2017-08-09 09:59 UTC, evgenyrodionov commented on src/components/main-section/product/product-color.js
> +        <button className="product-color-toggler-btn color-togl-black" type="button">black color</button>
togl? wtf is togl?

2017-08-09 14:00 UTC, flkrasnov commented on src/components/main-section/product/product-color.js
> +        <button className="product-color-toggler-btn color-togl-black" type="button">black color</button>
fixed

2017-08-09 14:00 UTC, flkrasnov commented on src/components/main-section/accordion/accordion.js
> +
fixed

2017-08-09 14:00 UTC, flkrasnov commented on src/components/main-section/accordion/accordion-heading.js
> +
fixed

2017-08-10 08:35 UTC, flkrasnov commented on src/components/main-section/accordion/accordion-heading.js
> +import React, { Component } from 'react';
fixed

2017-08-10 08:35 UTC, flkrasnov commented on src/components/main-section/accordion/accordion.js
> +const accordionHeadings = [
убрал

2017-08-10 10:14 UTC, imevro requested changes
Не стал проверять, структура неправильная, нейминг неправильный, стайлед-компонентс неправильны, сразу видно — не читал телеграф

2017-08-10 10:14 UTC, evgenyrodionov commented on public/index.html
> +  <link rel="stylesheet" href="https://unpkg.com/flexboxgrid2">
ставь через нпм

2017-08-10 10:14 UTC, evgenyrodionov commented on public/index.html
> +  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
через нпм

2017-08-10 10:14 UTC, evgenyrodionov commented on public/manifest.json
> +  "name": "Fake Burberry React Frontent",
Frontent

2017-08-10 10:14 UTC, evgenyrodionov commented on readme.md
> +- Desctop mock added
Desctop

2017-08-10 11:54 UTC, flkrasnov commented on public/index.html
> +  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
готово, забыл удалить из этого файла

2017-08-10 11:54 UTC, flkrasnov commented on public/index.html
> +  <link rel="stylesheet" href="https://unpkg.com/flexboxgrid2">
готово, забыл удалить из этого файла

2017-08-10 11:54 UTC, flkrasnov commented on public/manifest.json
> +  "name": "Fake Burberry React Frontent",
фикс

2017-08-10 11:54 UTC, flkrasnov commented on readme.md
> +- Desctop mock added
фикс

2017-08-10 16:55 UTC, flkrasnov commented
- Изменил структуру, было бы не плохо более подробно об этом узнать, мб будет какая-нибудь статья?
- Изменил нейминг всех компонентов.
- Исправил все ошибки в стайлед-компонентс.

ЗЫ Телеграф читал на самом деле, просто оставлял форматирование вот этого вот всего на потом, **буду следить за стилем**.

2017-08-10 18:07 UTC, evgenyrodionov commented
По структуре я в телеграфе писал

2017-08-10 18:10 UTC, imevro requested changes

2017-08-10 18:10 UTC, evgenyrodionov commented on src/App.js
>  class App extends Component {
зачем тут класс

2017-08-10 18:10 UTC, evgenyrodionov commented on src/Footer/FooterNav.jsx
> +            <ListAncor href="/">Payment</ListAncor>
listancor? Что это вообще значит?

2017-08-10 18:10 UTC, evgenyrodionov commented on src/Footer/FooterNav.jsx
> +            <ListAncor href="/">Payment</ListAncor>
как обычная ссылка стала LIST ANCOR?

2017-08-10 18:10 UTC, evgenyrodionov commented on src/Product/Product.jsx
> +import ProductHeader from "./ProductHeader";
product product product product product product product product product product product product product product product product product product product product product product product product product product product product product product product product product product product

2017-08-10 18:10 UTC, evgenyrodionov commented on src/Product/ProductButtons.jsx
> +function Button(props) {
композиция компонентов это хорошо, но я не понял что тебе мешает сразу использовать стайлед-компонент. только из-за props.value в чилдрене? так это и не вэлью!

2017-08-10 18:10 UTC, evgenyrodionov commented on src/Product/ProductColor.jsx
> +      {props.name} color is chosen
почему в настоящем времени? это call to ACTION

2017-08-10 18:10 UTC, evgenyrodionov commented on src/Product/Recomendations.jsx
> +      <BlockName>
зачем префикс блок блок блок?

2017-08-10 18:10 UTC, evgenyrodionov commented on src/Product/Recomendations.jsx
> +              <RecommendationBlock link="/" img="img/wr2.jpg" alt="Relaxed Fit Stretch Jeans" name="Relaxed Fit Stretch Jeans Content For Three Lines" price="22 500 руб" />
цену передавай числом, не строкой

2017-08-10 18:23 UTC, flkrasnov commented on src/App.js
>  class App extends Component {
согласен, фиксд

2017-08-10 18:25 UTC, flkrasnov commented on src/Footer/FooterNav.jsx
> +            <ListAncor href="/">Payment</ListAncor>
фиксд

2017-08-10 18:27 UTC, flkrasnov commented on src/Product/Product.jsx
> +import ProductHeader from "./ProductHeader";
фиксд

2017-08-10 18:30 UTC, flkrasnov commented on src/Product/Recomendations.jsx
> +      <BlockName>
фиксд

2017-08-10 18:33 UTC, flkrasnov commented on src/Product/Recomendations.jsx
> +              <RecommendationBlock link="/" img="img/wr2.jpg" alt="Relaxed Fit Stretch Jeans" name="Relaxed Fit Stretch Jeans Content For Three Lines" price="22 500 руб" />
фиксд

2017-08-10 18:34 UTC, flkrasnov commented on src/Product/ProductColor.jsx
> +      {props.name} color is chosen
заменил на "choose {props.name} color", если я правильно тебя понял

2017-08-10 19:36 UTC, flkrasnov commented on src/Product/ProductButtons.jsx
> +function Button(props) {
фиксд

2017-08-12 11:46 UTC, imevro requested changes

2017-08-12 11:46 UTC, imevro commented on src/Accordion/Delivery.jsx
> +    .accordion-row-head {
либо стайлед, либо обычный цсс

2017-08-12 11:46 UTC, imevro commented on src/Accordion/Delivery.jsx
> +            <Heading content="Description" />
почему не между тегов? зачем проп заводить?

2017-08-12 11:46 UTC, imevro commented on src/Accordion/Delivery.jsx
> +            <div className="col-xs-12 col-sm-7 col-lg-7">
нет нужды эксклюзивно прописывать lg-7, если ниже уже стоит sm-7 — 7 колонок наследуются пока не встретится другое правило

2017-08-12 11:46 UTC, imevro commented on src/Footer/FooterNav.jsx
> +            <Ancor href="/">Accessibility Statement</Ancor>
почему бы не Link?

2017-08-12 11:46 UTC, imevro commented on src/Product/Product.jsx
> +import Color from "./ProductColor";
слишком много продакт продакт продакт продакт

2017-08-12 11:46 UTC, imevro commented on src/common/HiddenMax.jsx
> +import React from "react";
а зачем столько компонентов? заведи один Responsive.jsx с несколькими экспротами

2017-08-12 11:46 UTC, imevro commented on src/common/ProductCode.jsx
> +export default () => {
а зачем эта прокладка? экспорти сразу СК

2017-08-12 11:46 UTC, imevro commented on src/Product/index.jsx
>  import Product from "./Product";
зачем делать Продакт в Продакте?

2017-08-12 12:11 UTC, flkrasnov commented on src/Accordion/Delivery.jsx
> +    .accordion-row-head {
не понимаю, как я это пропустил, пофиксил в СК

2017-08-12 13:06 UTC, flkrasnov commented on src/Accordion/Delivery.jsx
> +            <Heading content="Description" />
фиксд

2017-08-12 13:07 UTC, flkrasnov commented on src/Accordion/Delivery.jsx
> +            <div className="col-xs-12 col-sm-7 col-lg-7">
фиксд

2017-08-12 13:10 UTC, flkrasnov commented on src/Footer/FooterNav.jsx
> +            <Ancor href="/">Accessibility Statement</Ancor>
согласен

2017-08-12 13:10 UTC, flkrasnov commented on src/Product/Product.jsx
> +import Color from "./ProductColor";
фиксд

2017-08-12 13:10 UTC, flkrasnov commented on src/common/HiddenMax.jsx
> +import React from "react";
объединил

2017-08-12 19:05 UTC, imevro requested changes

2017-08-12 19:05 UTC, evgenyrodionov commented on src/Accordion/Delivery.jsx
> +import { HiddenMax, HiddenMin } from "../common/Hidden";
что-то мне неочевидно что эти компоненты вообще делают

2017-08-12 19:05 UTC, evgenyrodionov commented on src/Accordion/Delivery.jsx
> +              <FlexWrapper>
не очень очевидный нейминг у компонента

2017-08-12 19:05 UTC, evgenyrodionov commented on src/Accordion/Delivery.jsx
> +              <FlexWrapper>
зачем засорять нейминг реализацией? если завтра переделаешь на флоат, переименовывать будешь?

2017-08-12 19:05 UTC, evgenyrodionov commented on src/Product/Info.jsx
> +      <IntlProvider locale={props.locale}>
провайдер находится над всем приложением

2017-08-13 03:45 UTC, flkrasnov commented on src/Accordion/Delivery.jsx
> +              <FlexWrapper>
Переименовал во wrapper, у элементов нет обертки, а эта обертка контроллирует конкретное поведение на десктопе.

2017-08-13 11:24 UTC, imevro requested changes
исправишь — напиши в телеграм

2017-08-13 11:24 UTC, evgenyrodionov commented on src/Accordion/Delivery.jsx
> +import { DesctopHidden, DesctopVisible } from "../common/Hidden";
телеграф

2017-08-13 11:24 UTC, evgenyrodionov commented on src/Accordion/Delivery.jsx
> +import { DesctopHidden, DesctopVisible } from "../common/Hidden";
плюс desctop → desktop

2017-08-13 11:24 UTC, evgenyrodionov commented on src/common/Hidden.jsx
>    return <Responsive maxWidth={991} children={children} />;
телеграф

2017-08-13 14:26 UTC, flkrasnov commented
исправил нейминг на HiddenLg

2017-08-13 17:47 UTC, imevro approved these changes

2017-08-13 17:47 UTC, merged