Feat/ci
flkrasnov/fake-burrberry-frontend pull request #4
Opened 2017-08-15 14:13 UTC by flkrasnov

crlf to lf fixed,
eslint installed (bugfix),
husky installed (bugfix),
travis installed (bugfix) + proptypes installed and bugs fixed

2017-08-15 17:21 UTC, imevro requested changes

2017-08-15 17:21 UTC, evgenyrodionov commented on package.json
> +    "precommit": "eslint --ext .jsx,.js --fix src",
нет нужды 3 раза прописывать одно и то же, если можно просто npm run lint

2017-08-15 20:09 UTC, flkrasnov commented on package.json
> +    "precommit": "eslint --ext .jsx,.js --fix src",
http://prntscr.com/g8wcya

прекоммит с фиксом,
препуш поправил

2017-08-16 10:07 UTC, evgenyrodionov commented on package.json
> +    "precommit": "eslint --ext .jsx,.js --fix src",
хитро, красава

2017-08-16 10:08 UTC, imevro approved these changes

2017-08-16 10:08 UTC, merged