Fix/products cp
flkrasnov/fake-burrberry-frontend pull request #8
Opened 2017-08-19 10:53 UTC by flkrasnov

2017-08-19 16:30 UTC, flkrasnov commented
https://fake-burberry-npqkremdky.now.sh/

2017-08-19 20:06 UTC, evgenyrodionov commented
Шрифты у кнопок не те

![image](https://user-images.githubusercontent.com/775692/29489847-ff8ff976-8532-11e7-8f54-dc170290b391.png)
![image](https://user-images.githubusercontent.com/775692/29489848-01f7b9d8-8533-11e7-9ea8-b98595809651.png)

2017-08-19 20:08 UTC, evgenyrodionov commented
Тут слишком жирно
![image](https://user-images.githubusercontent.com/775692/29489850-095d1a24-8533-11e7-82b7-931a9ae90707.png)

Там бордер-боттом, а не текст-декорейшен
![image](https://user-images.githubusercontent.com/775692/29489865-32cce13c-8533-11e7-8e8e-75d8cecf1696.png)

2017-08-19 20:08 UTC, evgenyrodionov commented
Планшет
![image](https://user-images.githubusercontent.com/775692/29489869-48a997f2-8533-11e7-8f41-dcfb9078788f.png)

2017-08-19 20:09 UTC, evgenyrodionov commented
Кнопка без скруглений у тебя
![image](https://user-images.githubusercontent.com/775692/29489879-724613c4-8533-11e7-9126-58eaf17c6661.png)

2017-08-19 20:15 UTC, imevro requested changes

2017-08-19 20:15 UTC, evgenyrodionov commented on src/Footer/FooterNav.jsx
> +import { VisibleLg } from '../common/Responsive';
почему кстати этот файл (футернав) префиксуется "футер", если он и так лежит в директории футер?

2017-08-19 20:15 UTC, evgenyrodionov commented on src/Product.jsx
>  import ru from 'react-intl/locale-data/ru';
зачем ты файл переименовал из апп в продакт? втф?

2017-08-19 20:15 UTC, evgenyrodionov commented on src/Product/List/Category.jsx
> +            fit="Regular fit"
Это лейбл

2017-08-19 20:15 UTC, evgenyrodionov commented on src/Product/List/Filters/index.jsx
> +      <Heading>Men&apos;s Clothing</Heading>
как это относится к фильтрам?

2017-08-19 20:15 UTC, evgenyrodionov commented on src/Product/List/index.jsx
> +    <div className="container">
а почему 3 элемента сразу не засунуть в контейнер, зачем 3 контейнера

2017-08-19 20:15 UTC, evgenyrodionov commented on src/Product/List/index.jsx
> +    <More viewed={8} summ={17} count={9} />
это относится к категории

2017-08-19 20:15 UTC, evgenyrodionov commented on src/Product/Preview.jsx
> +      <AncorBlock to={props.link}>
to={link}?

2017-08-19 20:15 UTC, evgenyrodionov commented on src/Product/Preview.jsx
> +const AncorBlock = styled(Link)`
почему блок? а если это будет инлайном? как например 4 colours

2017-08-19 20:15 UTC, evgenyrodionov commented on src/index.js
> +function App() {
не понял почему у тебя реакт-интл не тут лежит, а каждый раз объявляется на странице?

плюс хедер/футер как бы одинаковые

2017-08-19 20:15 UTC, evgenyrodionov commented on src/index.js
> +import Product from './Product';
почему Product, но Product/View?

2017-08-19 20:15 UTC, evgenyrodionov commented on src/index.js
> +import ProductList from './ProductList';
Почему ProductList, но Product/List? где работа с index.jsx файлами?

2017-08-19 23:09 UTC, flkrasnov commented on src/Product/List/index.jsx
> +    <More viewed={8} summ={17} count={9} />
не понял, More должна быть внутри компонента категории?

2017-08-19 23:11 UTC, flkrasnov commented
все исправил

2017-08-20 01:08 UTC, flkrasnov commented
https://build-fqqpufexqm.now.sh

2017-08-20 07:07 UTC, flkrasnov commented
https://build-wqnjmpucqa.now.sh

2017-08-20 09:46 UTC, evgenyrodionov commented
Кнопки не того шрифта

2017-08-20 09:46 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/29493777-9ffbc1c0-85a5-11e7-9917-4add7ceff662.png)

2017-08-20 09:48 UTC, imevro requested changes
исправишь — смерджи через сквош

2017-08-20 09:48 UTC, evgenyrodionov commented on src/App.jsx
> +import ProductList from './Product/List';
можно просто Products

2017-08-20 09:48 UTC, evgenyrodionov commented on src/App.jsx
> +          <title>Long Cotton Gabardine Car Coat | Men - Burberry</title>
что это делает на главной странице?

2017-08-20 09:48 UTC, evgenyrodionov commented on src/Product/List/index.jsx
> +    <More viewed={8} summ={17} count={9} />
да

2017-08-20 16:28 UTC, flkrasnov commented
все готово

2017-08-20 16:39 UTC, flkrasnov commented
все исправил, смержил в мастер со сквошем. запушил мастер в ориджин

2017-08-20 16:40 UTC, flkrasnov commented
тут появились конфликты с fix/products-cp я их пофиксил и зачем-то смержил в нее мастера, хотя ветку (наверное?) можно удалять.

2017-08-22 17:25 UTC, evgenyrodionov commented
Я имел в виду эту кнопку

![image](https://user-images.githubusercontent.com/775692/29578459-0b9396e6-8778-11e7-84bb-8dc3bea84f61.png)

2017-08-22 17:25 UTC, closed without merging